/* dsh-sidebar-downloads — host half. Generated by scripts/build.mjs; edit src/ instead. */

// src/index.ts
import { homedir } from "node:os";
import { join } from "node:path";
import { readFileSync, readdirSync, statSync, unlinkSync } from "node:fs";
import { execFile } from "node:child_process";
var ARIA2_RPC = "http://127.0.0.1:16800/jsonrpc";
var ARIA2_TIMEOUT_MS = 1500;
var HOME = homedir();
var TASKS_DIR = join(HOME, ".dsh", "downloads", "tasks");
var API_PREFIX = "/api/sidebar-downloads";
var inject = ["webServer"];
var ACTIVE = /* @__PURE__ */ new Set(["downloading", "starting", "probing"]);
async function aria2Status(gid) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), ARIA2_TIMEOUT_MS);
  try {
    const res = await fetch(ARIA2_RPC, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ jsonrpc: "2.0", id: "sidebar-downloads", method: "aria2.tellStatus", params: [gid] }),
      signal: controller.signal
    });
    if (!res.ok) return void 0;
    const body = await res.json();
    return body.result;
  } catch {
    return void 0;
  } finally {
    clearTimeout(timer);
  }
}
function aria2TaskStatus(s) {
  switch (s) {
    case "active":
    case "waiting":
      return "downloading";
    case "paused":
      return "paused";
    case "complete":
      return "done";
    case "error":
      return "error";
    case "removed":
      return "cancelled";
    default:
      return "downloading";
  }
}
function mergeAria2(task, a) {
  const total = Number(a.totalLength ?? 0) || 0;
  const done = Number(a.completedLength ?? 0) || 0;
  const speed = Number(a.downloadSpeed ?? 0) || 0;
  const status = aria2TaskStatus(String(a.status ?? ""));
  const pct = total > 0 ? Math.min(100, Math.round(done / total * 1e3) / 10) : 0;
  const ariaPath = a.files?.[0]?.path ?? "";
  return {
    ...task,
    status,
    // aria2 reports byte counts as strings; numbers land here so the client
    // never has to care which producer wrote the record.
    total,
    downloaded: done,
    percent: pct,
    speedMBps: Math.round(speed / 1048576 * 100) / 100,
    etaSec: speed > 0 && total > 0 ? Math.round((total - done) / speed) : -1,
    error: String(a.errorMessage ?? "") || task.error,
    outPath: ariaPath !== "" ? ariaPath : task.outPath,
    // Byte count for a live transfer is the engine's, not a stat() of a file
    // that may be a preallocated sparse placeholder.
    bytesOnDisk: status === "done" ? task.outPath ? fileSize(ariaPath || task.outPath) : done : done,
    endedAt: status === "downloading" || status === "paused" ? 0 : task.endedAt || Date.now(),
    source: "aria2"
  };
}
async function readTasks() {
  let entries;
  try {
    entries = readdirSync(TASKS_DIR);
  } catch {
    return { tasks: [], dirExists: false, dir: TASKS_DIR };
  }
  const tasks = [];
  for (const name of entries) {
    if (!name.endsWith(".json")) continue;
    const taskId = name.slice(0, -".json".length);
    try {
      const obj = parseRecord(readFileSync(join(TASKS_DIR, name), "utf8"));
      if (obj === null || typeof obj !== "object") continue;
      const name_ = str(obj.name);
      if (name_ === "") continue;
      tasks.push({
        taskId,
        name: name_,
        url: str(obj.url),
        finalUrl: str(obj.finalUrl),
        outPath: str(obj.outPath),
        status: str(obj.status) || "unknown",
        error: str(obj.error),
        total: num(obj.total),
        downloaded: num(obj.downloaded),
        // percent is -1 when the server sent no Content-Length.
        percent: num(obj.percent),
        speedMBps: num(obj.speedMBps),
        elapsedSec: num(obj.elapsedSec),
        etaSec: num(obj.etaSec),
        startedAt: num(obj.startedAt),
        endedAt: num(obj.endedAt),
        // Bytes actually on disk right now, which is authoritative when a
        // download was killed without writing a final record.
        bytesOnDisk: fileSize(obj.outPath),
        gid: str(obj.gid),
        source: "ledger"
      });
    } catch {
    }
  }
  const live = tasks.filter((t) => t.gid !== "");
  if (live.length > 0) {
    const statuses = await Promise.all(live.map((t) => aria2Status(t.gid)));
    for (let i = 0; i < live.length; i += 1) {
      const status = statuses[i];
      const task = live[i];
      if (status === void 0 || task === void 0) continue;
      const merged = mergeAria2(task, status);
      const at = tasks.indexOf(task);
      if (at >= 0) tasks[at] = merged;
    }
  }
  tasks.sort((a, b) => {
    const ra = ACTIVE.has(a.status) ? 0 : 1;
    const rb = ACTIVE.has(b.status) ? 0 : 1;
    if (ra !== rb) return ra - rb;
    return (b.startedAt || b.endedAt || 0) - (a.startedAt || a.endedAt || 0);
  });
  return { tasks, dirExists: true, dir: TASKS_DIR };
}
function parseRecord(text) {
  const clean = text.charCodeAt(0) === 65279 ? text.slice(1) : text;
  return JSON.parse(clean);
}
function str(v) {
  return typeof v === "string" ? v : "";
}
function num(v) {
  return typeof v === "number" && Number.isFinite(v) ? v : 0;
}
function fileSize(path) {
  if (typeof path !== "string" || path === "") return 0;
  try {
    return statSync(path).size;
  } catch {
    return 0;
  }
}
function sendJson(res, code, payload) {
  try {
    res.writeHead(code, { "Content-Type": "application/json; charset=utf-8" });
    res.end(JSON.stringify(payload));
  } catch {
  }
}
function taskFile(taskId) {
  if (typeof taskId !== "string" || taskId === "") return void 0;
  if (taskId.includes("/") || taskId.includes("\\") || taskId.includes("..")) return void 0;
  return join(TASKS_DIR, taskId + ".json");
}
function apply(ctx) {
  ctx.effect(
    () => ctx.webServer.register({
      kind: "prefix",
      path: API_PREFIX,
      handler: async (req, res) => {
        const url = new URL(req.url ?? "/", "http://localhost");
        const route = url.pathname.startsWith(API_PREFIX) ? url.pathname.slice(API_PREFIX.length) || "/" : "/";
        if (route === "/tasks") {
          const ledger = await readTasks();
          return sendJson(res, 200, {
            ok: true,
            tasks: ledger.tasks,
            active: ledger.tasks.filter((t) => ACTIVE.has(t.status)).length,
            // Lets the panel say "the ledger is gone" instead of showing a
            // stale list or a misleading "no downloads".
            dirExists: ledger.dirExists,
            dir: ledger.dir
          });
        }
        if (route === "/reveal") {
          const file = taskFile(url.searchParams.get("taskId") ?? "");
          if (file === void 0) return sendJson(res, 400, { ok: false, error: "taskId \u975E\u6CD5" });
          let outPath = "";
          try {
            outPath = JSON.parse(readFileSync(file, "utf8")).outPath ?? "";
          } catch {
            return sendJson(res, 404, { ok: false, error: "\u8BE5\u4EFB\u52A1\u8BB0\u5F55\u5DF2\u4E0D\u5B58\u5728", stale: true });
          }
          if (!outPath) return sendJson(res, 404, { ok: false, error: "\u4EFB\u52A1\u7F3A\u5C11\u8F93\u51FA\u8DEF\u5F84", stale: false });
          execFile("explorer.exe", ["/select," + outPath], { windowsHide: true }, () => {
          });
          return sendJson(res, 200, { ok: true });
        }
        if (route === "/forget") {
          const file = taskFile(url.searchParams.get("taskId") ?? "");
          if (file === void 0) return sendJson(res, 400, { ok: false, error: "taskId \u975E\u6CD5" });
          try {
            unlinkSync(file);
            return sendJson(res, 200, { ok: true });
          } catch {
            return sendJson(res, 404, { ok: false, error: "\u8BB0\u5F55\u4E0D\u5B58\u5728" });
          }
        }
        return sendJson(res, 404, { ok: false, error: "unknown route" });
      }
    }),
    "dsh-sidebar-downloads: api routes"
  );
}
export {
  API_PREFIX,
  apply,
  inject
};
