/**
 * Build script for dsh-sidebar-downloads.
 *
 * Produces two artifacts, both committed so the package installs straight
 * from a git URL with no build step on the user's machine:
 *
 * - lib/index.js  — the host half, plain ESM for Node.
 * - lib/client.js — the browser half, wrapped in DSH's client module-loader
 *   envelope (`window.__ModuleLoader__.load({ id, factory })`). React and
 *   the JSX runtime are pulled from the host through `require(...)` so the
 *   bundle shares the host's React instance; CSS Modules are compiled to a
 *   hashed class map and injected as a single <style> tag guarded by a
 *   data attribute, which makes re-activation (HMR) idempotent.
 */
import { build, context } from 'esbuild'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { createHash } from 'node:crypto'
import { transform } from 'lightningcss'
import { dirname, join } from 'node:path'

const root = dirname(fileURLToPath(new URL('.', import.meta.url)))
const outDir = join(root, 'lib')
const PLUGIN_ID = 'dsh-sidebar-downloads'

/** Compile one CSS module file into { classMap, css } via lightningcss. */
async function compileCssModule(file) {
  const source = await readFile(file)
  const { code, exports: cssExports } = transform({
    filename: file,
    code: source,
    cssModules: { pattern: '[hash]_[local]' },
    minify: true,
  })
  // lightningcss returns exports as { localName: { name, isReferenced } }.
  const classMap = {}
  for (const [local, info] of Object.entries(cssExports ?? {})) {
    classMap[local] = info.name
  }
  return { classMap, css: code.toString() }
}

/** Resolve *.module.css imports into a virtual JS module exporting the map. */
const cssModulePlugin = {
  name: 'dsh-css-modules',
  setup(b) {
    b.onLoad({ filter: /\.module\.css$/ }, async (args) => {
      const { classMap, css } = await compileCssModule(args.path)
      // Each stylesheet carries a content hash so a changed stylesheet gets a
      // fresh style tag while an unchanged one is reused.
      const hash = createHash('sha256').update(css).digest('hex').slice(0, 12)
      const tagId = PLUGIN_ID + '/' + hash
      const contents = [
        'const __map = ' + JSON.stringify(classMap) + ';',
        'const __css = ' + JSON.stringify(css) + ';',
        'const __id = ' + JSON.stringify(tagId) + ';',
        "if (typeof document !== 'undefined') {",
        "  if (document.querySelector('style[data-plugin-css=\"' + __id + '\"]') === null) {",
        "    const tag = document.createElement('style');",
        '    tag.dataset.pluginCss = __id;',
        '    tag.dataset.plugin = ' + JSON.stringify(PLUGIN_ID) + ';',
        '    tag.textContent = __css;',
        '    document.head.appendChild(tag);',
        '  }',
        '}',
        'export default __map;',
      ].join('\n')
      return { contents, loader: 'js' }
    })
  },
}

const shared = {
  bundle: true,
  minify: false,
  sourcemap: false,
  logLevel: 'info',
}

async function run({ watch = false } = {}) {
  await mkdir(outDir, { recursive: true })

  // ---- host half: plain ESM, node built-ins external ----
  const hostOptions = {
    ...shared,
    entryPoints: [join(root, 'src/index.ts')],
    outfile: join(outDir, 'index.js'),
    format: 'esm',
    platform: 'node',
    target: 'node20',
    packages: 'external',
    banner: {
      js: '/* dsh-sidebar-downloads — host half. Generated by scripts/build.mjs; edit src/ instead. */',
    },
  }

  // ---- client half: IIFE wrapped in the module-loader envelope ----
  const clientOptions = {
    ...shared,
    entryPoints: [join(root, 'src/client/bundle-entry.ts')],
    outfile: join(outDir, '.client.raw.js'),
    format: 'iife',
    platform: 'browser',
    target: 'es2022',
    // Host-provided singletons: React must be the host's instance, or hooks
    // break. Everything else is bundled.
    external: ['react', 'react-dom', 'react/jsx-runtime', 'react-dom/client', 'cordis'],
    jsx: 'automatic',
    plugins: [cssModulePlugin],
  }

  if (watch) {
    const hostCtx = await context(hostOptions)
    const clientCtx = await context(clientOptions)
    await hostCtx.watch()
    await clientCtx.watch()
    console.log('[dsh-sidebar-downloads] watching…')
    return
  }

  await build(hostOptions)
  await build(clientOptions)
  await wrapClient()
  console.log('[dsh-sidebar-downloads] built lib/index.js + lib/client.js')
}

/** Wrap the raw IIFE in the loader envelope and write lib/client.js. */
async function wrapClient() {
  const raw = await readFile(join(outDir, '.client.raw.js'), 'utf8')
  // The IIFE assigns its exports onto a global the wrapper reads back.
  const wrapped = [
    '/* dsh-sidebar-downloads — client half. Generated by scripts/build.mjs; edit src/ instead. */',
    'window.__ModuleLoader__.load({',
    '  id: ' + JSON.stringify(PLUGIN_ID) + ',',
    '  factory: (require) => {',
    '    var module = { exports: {} };',
    '    var exports = module.exports;',
    '    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });',
    "    // `require` reaches the host's module table (react, jsx runtime) so",
    '    // this bundle shares the host React instance instead of bundling one.',
    '    var __dshRequire = require;',
    raw,
    '    var __api = globalThis.__dshExports;',
    '    if (__api === undefined) {',
    "      throw new Error('dsh-sidebar-downloads: client bundle did not publish its exports');",
    '    }',
    '    exports.apply = __api.apply;',
    '    exports.inject = __api.inject;',
    '    return module.exports;',
    '  },',
    '});',
  ].join('\n')
  await writeFile(join(outDir, 'client.js'), wrapped, 'utf8')
}

await run({ watch: process.argv.includes('--watch') })
